vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
spring:
  mustache:
    check-template-location: 'false'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 500MB
logging:
  level:
    org:
      atmosphere: warn

server:
  port: ${PORT:8080}

model:
  base-url: http://localhost:8000
  resize-images: false